using System.Collections.Generic;
using System.Collections;
using UnityEngine;
using DG.Tweening;
using UnityEngine.UI;
using System.Linq;
using TMPro;
using System;


public class BonusGame : MonoBehaviour
{
    [Header("Sprites")]
    [SerializeField]
    private Sprite[] myImages;

    [Header("Slot Images")]
    [SerializeField]
    private List<SlotImage> Tempimages;

    [Header("Slots Objects")]
    [SerializeField]
    private GameObject[] Slot_Objects;
    [Header("Slots Elements")]
    [SerializeField]
    private LayoutElement[] Slot_Elements;

    [Header("Slots Transforms")]
    [SerializeField]
    private Transform[] Slot_Transform;

    int tweenHeight = 0;  //calculate the height at which tweening is done

    [SerializeField]
    private GameObject Image_Prefab;    //icons prefab

    [SerializeField]
    private PayoutCalculation PayCalculator;

    private List<Tweener> alltweens = new List<Tweener>();


    [SerializeField]
    private List<ImageAnimation> TempList;

    [SerializeField]
    private int IconSizeFactor = 100;

    private int numberOfSlots = 3;

    [SerializeField]
    int verticalVisibility = 3;

    [SerializeField]
    private SocketIOManager SocketManager;
    [SerializeField] private SlotBehaviour slotBehaviour;

    [SerializeField] private int stopIndex;
    [SerializeField] private Sprite exitSprite;
    [SerializeField] private GameObject bonusGame;
    [SerializeField] private List<Transform> OuterReelSlots;
    [SerializeField] private GameObject OuterSlotItemPrefab;

    [SerializeField] private List<OuterReelItem> Outer_Reel_All_Item;
    [SerializeField] private GameObject lighting;

    [SerializeField] private GameManager m_GameManager;

    [Header("Data Update Section")]
    [SerializeField] private TMP_Text m_Lives;
    [SerializeField] private TMP_Text m_Amount;
    [SerializeField] private TMP_Text m_TotalWonAmount;

    [SerializeField] private List<int> animIndex = new List<int>();
    [SerializeField] private int m_SpaceFactor;

    [Header("Outer Reel References Section")]
    [SerializeField] private List<OuterReelItem> m_FruitCockTail;
    [SerializeField] private List<OuterReelItem> m_WaterMelon;
    [SerializeField] private List<OuterReelItem> m_Peer;
    [SerializeField] private List<OuterReelItem> m_Coconut;
    [SerializeField] private List<OuterReelItem> m_Pineapple;
    [SerializeField] private List<OuterReelItem> m_Orange;
    [SerializeField] private List<OuterReelItem> m_Cherry;
    [SerializeField] private List<OuterReelItem> m_Exit;

    [SerializeField] private GameObject m_StopGameobject;
    [SerializeField] private GameObject m_BonusWonPopup;

    BonusResult m_DefaultStructure;
    BonusResult m_ReceivedStructure;

    private bool ison = true;
    public List<int> resultnum = new List<int>();
    private int Lives = 0;
    private int N_SpinCount_Begin = 0;
    private int N_SpinCount = 0;
    private Coroutine m_Spinning;
    private Coroutine tweenroutine;
    private bool IsSpinning;

    private void Start()
    {
        InvokeRepeating("ToggleOnOff", 0.1f, 0.2f);
        tweenHeight = (myImages.Length * IconSizeFactor) - 280;

        m_DefaultStructure = new BonusResult
        {
            innerMatrix = new List<List<int>> { new List<int> { 5, 5, 6 }, new List<int> { 6, 6, 3 }, new List<int> { 2, 3, 4 } },
            outerRingSymbol = new List<int> { 5, 3, 7 },
            totalWinAmount = 2.5,
            winings = new List<string> { "1.0", "1.0", "0" }
        };
    }

    //just for testing purposes delete on production
    //private void Update()
    //{
    //    if (Input.GetKeyDown(KeyCode.B))
    //    {
    //        StartBonus(m_DefaultStructure.winings.Count, m_DefaultStructure);
    //        StartBonusGame();
    //    }
    //}

    internal void StartBonusGame()
    {
        m_GameManager.m_AudioController.m_BG_Audio.Stop();
        m_GameManager.m_AudioController.m_Bonus_BG_Audio.Play();
        bonusGame.SetActive(true);
        if (!IsSpinning)
        {
            IsSpinning = true;

            if (m_Spinning != null)
            {
                StopCoroutine(m_Spinning);
                m_Spinning = null;
            }
            m_Spinning = StartCoroutine(AutoSpinCoroutine());
        }
    }

    internal void StartBonus(int m_count, BonusResult m_BonusData)
    {
        m_ReceivedStructure = m_BonusData;
        N_SpinCount = m_count;
        m_StopGameobject = null;
        N_SpinCount_Begin = 0;
        Lives = m_ReceivedStructure.outerRingSymbol.Count(x => x == 7);
        m_TotalWonAmount.text = m_ReceivedStructure.totalWinAmount.ToString();
    }

    //starts the spin process
    private void StartSlots(bool autoSpin = false)
    {
        if (TempList.Count > 0)
        {
            StopGameAnimation();
        }

        PayCalculator.ResetLines();

        tweenroutine = StartCoroutine(TweenRoutine());
    }

    private void StopAutoSpin()
    {
        //if (audioController) audioController.PlaySpinButtonAudio();

        if (IsSpinning)
        {
            IsSpinning = false;
            StartCoroutine(StopAutoSpinCoroutine());
        }
    }

    private IEnumerator AutoSpinCoroutine()
    {
        yield return new WaitForSeconds(0.4f);

        for(int i = 0; i < N_SpinCount; i ++)
        {
            StartSlots(IsSpinning);
            yield return tweenroutine;
        }

        yield return new WaitForSeconds(0.2f);

        bonusGame.SetActive(false);
        m_GameManager.m_AudioController.m_Bonus_Audio.Play();
        m_GameManager.m_PushObject(m_BonusWonPopup);

        yield return new WaitForSeconds(3f);

        StopAutoSpin();
        Reset();
        slotBehaviour.ToggleButtonGrp(true);
    }

    private IEnumerator StopAutoSpinCoroutine()
    {
        yield return new WaitUntil(() => !IsSpinning);
        if (m_Spinning != null || tweenroutine != null)
        {
            try
            {
                StopCoroutine(m_Spinning);
                StopCoroutine(tweenroutine);
                tweenroutine = null;
                m_Spinning = null;
                StopCoroutine(StopAutoSpinCoroutine());
            }
            catch (Exception e)
            {
                Debug.Log("Error Occured..." + string.Concat("<color=red><b>", e, "</b></color>"));
            }
        }
    }

    //manage the Routine for spinning of the slots
    private IEnumerator TweenRoutine()
    {
        IsSpinning = true;
        StopInnerAnimations();
        m_Lives.text = Lives.ToString();

        m_GameManager.m_AudioController.m_Spin_Audio.Play();

        Coroutine moveSelector = StartCoroutine(ToggleSelectorAnimation(0.08f, 2));

        yield return new WaitForSeconds(0.1f);

        for (int i = 0; i < numberOfSlots; i++)
        {
            InitializeTweening(Slot_Transform[i]);
            yield return new WaitForSeconds(0.1f);
        }

        yield return new WaitForSeconds(0.5f);

        m_StopGameobject = PopulateOuterMatrix(m_ReceivedStructure.outerRingSymbol[N_SpinCount_Begin]);

        PopulateInnerMatrix();

        for (int i = 0; i < numberOfSlots; i++)
        {
            yield return StopTweening(5, Slot_Transform[i], i);
        }

        yield return moveSelector;

        m_GameManager.m_AudioController.m_Spin_Audio.Stop();

        m_Lives.text = Lives.ToString();

        if(m_ReceivedStructure.outerRingSymbol[N_SpinCount_Begin - 1] != 7)
        {
            PlayInnerAnimations();
        }

        CheckPayoutLineBackend(resultnum);

        m_Amount.text = (m_ReceivedStructure.winings[N_SpinCount_Begin - 1]).ToString();

        yield return new WaitForSeconds(3f);
        KillAllTweens();
    }


    private void CheckPayoutLineBackend(List<int> numbers)
    {

        for (int i = 0; i < animIndex.Count; i++)
        {
            StartGameAnimation(Tempimages[animIndex[i]].slotImages[0].gameObject);
        }

    }

    private void StartGameAnimation(GameObject animObjects)
    {

        Tweener tweener = animObjects.transform.DOScale(Vector3.one * 1.1f, 0.5f).SetLoops(-1, LoopType.Yoyo);
        alltweens.Add(tweener);
    }

    private void StopGameAnimation()
    {
        for (int i = 0; i < TempList.Count; i++)
        {
            TempList[i].StopAnimation();
        }
    }

    void ToggleOnOff()
    {
        ison = !ison;
        lighting.SetActive(ison);

    }

    private void Reset()
    {
        StopGameAnimation();
        ResetHighlights();
        m_GameManager.m_PopObject();
        m_GameManager.m_AudioController.m_Bonus_BG_Audio.Stop();
        m_GameManager.m_AudioController.m_BG_Audio.Play();
    }

    private void ResetHighlights()
    {
        foreach (OuterReelItem item in Outer_Reel_All_Item)
        {
            item.selector.SetActive(false);
        }
    }

    private void PopulateInnerMatrix()
    {
        for(int i = 0; i < Tempimages.Count; i++)
        {
            Tempimages[i].slotImages[0].transform.GetChild(0).GetComponent<Image>().sprite = myImages[m_ReceivedStructure.innerMatrix[N_SpinCount_Begin][i]];
            Tempimages[i].slotImages[0].GetComponent<OuterReelItem>().image.GetComponent<ImageAnimation>().textureArray = GetSpriteList(m_ReceivedStructure.innerMatrix[N_SpinCount_Begin][i]).ToList();
        }
        if(N_SpinCount_Begin < N_SpinCount)
        {
            N_SpinCount_Begin++;
        }
    }

    private Sprite[] GetSpriteList(int m_value)
    {
        switch (m_value)
        {
            case 0://FRUITCOCKTAIL
                return slotBehaviour.Juice_Sprite;
            case 1://WATERMELON
                return slotBehaviour.Watermelon_Sprite;
            case 2://PEER
                return slotBehaviour.Pear_Sprite;
            case 3://COCONUT
                return slotBehaviour.Coconut_Sprite;
            case 4://PINEAPPLE
                return slotBehaviour.Pineapple_Sprite;
            case 5://ORANGE
                return slotBehaviour.Orange_Sprite;
            case 6://CHERRY
                return slotBehaviour.Cherry_Sprite;
            case 7://EXIT
                break;
        }
        return null;
    }

    private void PlayInnerAnimations()
    {
        for(int i = 0; i < Tempimages.Count; i++)
        {
            Tempimages[i].slotImages[0].GetComponent<OuterReelItem>().image.GetComponent<ImageAnimation>().StartAnimation();
        }
    }

    private void StopInnerAnimations()
    {
        for (int i = 0; i < Tempimages.Count; i++)
        {
            Tempimages[i].slotImages[0].GetComponent<OuterReelItem>().image.GetComponent<ImageAnimation>().StopAnimation();
            Tempimages[i].slotImages[0].GetComponent<OuterReelItem>().image.GetComponent<ImageAnimation>().textureArray.Clear();
            Tempimages[i].slotImages[0].GetComponent<OuterReelItem>().image.GetComponent<ImageAnimation>().textureArray.TrimExcess();
        }
    }

    private GameObject PopulateOuterMatrix(int m_value)
    {
        int random_index;
        switch (m_value)
        {
            case 0://FRUITCOCKTAIL
                random_index = UnityEngine.Random.Range(0, m_FruitCockTail.Count);
                return m_FruitCockTail[random_index].gameObject;
            case 1://WATERMELON
                random_index = UnityEngine.Random.Range(0, m_WaterMelon.Count);
                return m_WaterMelon[random_index].gameObject;
            case 2://PEER
                random_index = UnityEngine.Random.Range(0, m_Peer.Count);
                return m_Peer[random_index].gameObject;
            case 3://COCONUT
                random_index = UnityEngine.Random.Range(0, m_Coconut.Count);
                return m_Coconut[random_index].gameObject;
            case 4://PINEAPPLE
                random_index = UnityEngine.Random.Range(0, m_Pineapple.Count);
                return m_Pineapple[random_index].gameObject;
            case 5://ORANGE
                random_index = UnityEngine.Random.Range(0, m_Orange.Count);
                return m_Orange[random_index].gameObject;
            case 6://CHERRY
                random_index = UnityEngine.Random.Range(0, m_Cherry.Count);
                return m_Cherry[random_index].gameObject;
            case 7://EXIT
                random_index = UnityEngine.Random.Range(0, m_Exit.Count);
                Lives--;
                return m_Exit[random_index].gameObject;
        }

        return null;
    }

    #region [[===TWEENING CODE===]]

    private void InitializeTweening(Transform slotTransform)
    {
        slotTransform.localPosition = new Vector2(slotTransform.localPosition.x, 0);
        Tweener tweener = slotTransform.DOLocalMoveY(-tweenHeight, 1.2f).SetLoops(-1, LoopType.Restart).SetEase(Ease.Linear).SetDelay(0);
        tweener.Play();
        alltweens.Add(tweener);
    }

    private IEnumerator StopTweening(int reqpos, Transform slotTransform, int index)
    {
        bool IsRegister = false;
        yield return alltweens[index].OnStepComplete(delegate { IsRegister = true; });
        yield return new WaitUntil(() => IsRegister);
        alltweens[index].Kill();
        //alltweens[index].Pause();
        int tweenpos = (reqpos * (IconSizeFactor + m_SpaceFactor)) - (IconSizeFactor + (2 * m_SpaceFactor)) + 20;
        //alltweens[index] = slotTransform.DOLocalMoveY(-tweenpos - 100 - 40, 0.5f).SetEase(Ease.OutElastic);
        alltweens[index] = slotTransform.DOLocalMoveY((-tweenpos + (100)) + (m_SpaceFactor > 0 ? m_SpaceFactor / 4 : 0), 1.1f).SetEase(Ease.OutQuad);
        //yield return new WaitForSeconds(0.2f);
        yield return alltweens[index].WaitForCompletion();
        alltweens[index].Kill();
    }

    //HACK: Killing all initialized tweens to stop tweens.
    private void KillAllTweens()
    {
        for (int i = 0; i < alltweens.Count; i++)
        {
            alltweens[i].Kill();
        }
        alltweens.Clear();

    }

    //HACK: This coroutine is used to run the border of the boxes one after another.
    IEnumerator ToggleSelectorAnimation(float delay, int noOfRotation = 1)
    {
        int count = 0;
        ResetHighlights();
        for (int j = 0; j < noOfRotation + 1; j++)
        {
            for(int i = Outer_Reel_All_Item.Count - 1; i > 0; i--)
            {
                Outer_Reel_All_Item[i].selector.SetActive(true);
                if (j == noOfRotation && Outer_Reel_All_Item[i].gameObject == m_StopGameobject)
                {
                    Outer_Reel_All_Item[i].selector.SetActive(true);
                    slotBehaviour.CheckPopups = false;
                    yield return new WaitForSeconds(0.2f);
                    yield break;
                }
                if (j < noOfRotation)
                {
                    yield return new WaitForSeconds(delay);
                }
                else
                {
                    count = 0;
                    if(count < 4)
                    {
                        count++;
                        yield return new WaitForSeconds(delay * 2f);
                    }
                    else
                    {
                        yield return new WaitForSeconds(delay * 4f);
                    }
                }
                Outer_Reel_All_Item[i].selector.SetActive(false);
            }
        }
        yield return new WaitForSeconds(0.6f);
    }
    #endregion
}